.PHONY: clean All

All:
	@echo "----------Building project:[ RTS-Lab - Debug ]----------"
	@cd "/Users/mbrattlof/Google Drive/School/Chalmers 2018-2019/EDA422 - Parallel and distributed RTS/Labs/HWA1/Part1/RTS-Lab" && "$(MAKE)" -f  "RTS-Lab.mk" && "$(MAKE)" -f  "RTS-Lab.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ RTS-Lab - Debug ]----------"
	@cd "/Users/mbrattlof/Google Drive/School/Chalmers 2018-2019/EDA422 - Parallel and distributed RTS/Labs/HWA1/Part1/RTS-Lab" && "$(MAKE)" -f  "RTS-Lab.mk" clean
